#!/usr/bin/env bash

echo
echo "* : Expands to the positional parameters"
echo "The positional parameters are: $*"

echo
echo "@ : Expands to the positional parameters"
echo "The positional parameters are: $@"

echo
echo "# : Expands to the number of positional parameters"
echo "The number of positional parameters is: $#"

echo
echo "? : Expands to the exit status of the most recently executed foreground pipeline"
echo "The exit status of the last foreground pipeline is $?"

set -o errexit

echo
echo "- : Expands to the current option flags specified by the \`set\` builtin or the shell itself"
echo "The current option flags are $-"

echo
echo "$ : Expands to the process ID of the shell"
echo "The shell process ID is $$"

echo&

echo
echo "! : Expands to the process ID of the job most recently placed into the background"
echo "The most recent background process ID is $!"

echo
echo "0 : Expands to the name of the shell or shell script"
echo "The name of this script is \`$0\`"

